language: rust

cache: cargo

rust:
  - nightly

before_script:
  - rustup component add rustfmt-nightly

script:
  - cargo fmt -- --check
  - cargo build --verbose --all
  - cargo test --verbose --all
