language: rust

cache: cargo

rust:
  - nightly

install:
  - rustup component add rustfmt-nightly

script:
  - cargo fmt -- --check --write-mode=diff
  - cargo build --verbose --all
  - cargo test --verbose --all
